name: BuildImage

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get latest image tag
        run: |
          readarray -t tags < <(curl -L -s 'https://registry.hub.docker.com/v2/repositories/anmalkov/osv-scanner/tags?page_size=1024' | jq '."results"[]["name"]' | tr -d '"')
          latest_tag=${tags[0]}
          if [[ $latest_tag == "latest" ]];
          then  
            latest_tag=${tags[1]}
          fi
          echo "Latest image tag: $latest_tag"
          echo "latest_tag=$latest_tag" >> $GITHUB_ENV
      - name: Get latest release
        run: |
          release_url=$(curl -Ls -o /dev/null -w %{url_effective} https://github.com/google/osv-scanner/releases/latest)
          latest_release=$(basename $release_url)
          echo "Latest release: $latest_release"
          echo "latest_release=$latest_release" >> $GITHUB_ENV
          
          
